# Generated by Django 4.1.7 on 2023-04-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartItem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cartid',
        ),
    ]
