# Generated by Django 4.1.7 on 2023-04-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('category', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=500)),
                ('price', models.IntegerField(max_length=1000)),
                ('unitprice', models.IntegerField(max_length=1000)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
